apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zglosto-ha
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: '3'
  replicaSoftAntiAffinity: disabled
  fsType: ext4
