packages:
  - 'frontend'
  - 'backend'
  - 'authorization'
  - 'llm_gateway'
  - 'Mobile'
  - 'packages/*'
injectWorkspacePackages: true
resolvePeersFromWorkspaceRoot: false
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
overrides:
  '@babel/core': 7.29.7
  'query-string>decode-uri-component': 0.5.0
  'xcode>uuid': 11.1.1
  'xmlbuilder2>js-yaml': 4.3.1
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  esbuild: true
  protobufjs: true
