apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - network-policy.yaml

patches:
  - path: authorization-redis-patch.yaml
    target:
      kind: Deployment
      name: authorization
  - path: backend-redis-patch.yaml
    target:
      kind: Deployment
      name: backend
