// Reviewed sources only; the historical phase archive remains in Git.
export const pages = [
  {
    slug: 'start',
    source: 'docs/local-development.md',
    title: 'Uruchomienie lokalne',
    description: 'Wymagania, Docker Compose, dane demo i rozwiązywanie problemów.',
    group: 'Pierwsze kroki',
  },
  {
    slug: 'konfiguracja',
    source: 'docs/white-label-configuration.md',
    title: 'Konfiguracja miasta',
    description:
      'Własny YAML, branding, służby i języki — od konfiguracji do działającego WEB/API.',
    group: 'Pierwsze kroki',
  },
  {
    slug: 'mieszkaniec-web',
    source: 'docs/using-web-resident.md',
    title: 'Mieszkaniec w WEB',
    description: 'Publiczne sprawy, zgłoszenie, konto i prywatna historia.',
    group: 'Korzystanie z aplikacji',
  },
  {
    slug: 'sluzby-web',
    source: 'docs/using-web-service.md',
    title: 'Służby w WEB',
    description: 'Kolejka własnej służby, filtry, statusy i zdjęcie po naprawie.',
    group: 'Korzystanie z aplikacji',
  },
  {
    slug: 'administrator-web',
    source: 'docs/using-web-admin.md',
    title: 'Administrator w WEB',
    description: 'Wszystkie sprawy, nieprzypisane zgłoszenia i uprawnienia kont.',
    group: 'Korzystanie z aplikacji',
  },
  {
    slug: 'mieszkaniec-mobile',
    source: 'docs/using-mobile-resident.md',
    title: 'Mieszkaniec w Mobile',
    description: 'Publiczny feed, formularz, historia i konto na telefonie.',
    group: 'Korzystanie z aplikacji',
  },
  {
    slug: 'sluzby-mobile',
    source: 'docs/using-mobile-service.md',
    title: 'Służby w Mobile',
    description: 'Kolejka pracownika, status, weryfikacja i praca bez sieci.',
    group: 'Korzystanie z aplikacji',
  },
  {
    slug: 'architektura',
    source: 'docs/current-architecture-audit.md',
    title: 'Architektura systemu',
    description: 'Bieżący runtime, odpowiedzialność usług i granice integracji.',
    group: 'System',
  },
  {
    slug: 'media',
    source: 'docs/media-processing-contract.md',
    title: 'Przetwarzanie zdjęć',
    description: 'Upload, worker, kolejka, retry i prywatne obrazy.',
    group: 'System',
  },
  {
    slug: 'zgloszenia',
    source: 'docs/incident-acceptance.md',
    title: 'Przyjmowanie zgłoszeń',
    description: 'Wybór służby, potwierdzenie zapisu i pomocnicza rola LLM.',
    group: 'System',
  },
  {
    slug: 'wdrozenie',
    source: 'docs/deployment-selection.md',
    title: 'Wybór wdrożenia',
    description:
      'Compose, Kubernetes czy K3s? Dobierz profil, poznaj ograniczenia i przejdź do instrukcji.',
    group: 'Wdrożenie i utrzymanie',
  },
  {
    slug: 'operacje',
    source: 'docs/production-compose-runbook.md',
    title: 'Wdrożenie Compose',
    description: 'Przygotowanie hosta, HTTPS, aktualizacje i utrzymanie produkcji.',
    group: 'Wdrożenie i utrzymanie',
  },
  {
    slug: 'profile',
    source: 'docs/infrastructure-profiles.md',
    title: 'Kubernetes i K3s',
    description: 'Wybór profilu, ograniczenia dostępności i odzyskiwanie klastra.',
    group: 'Wdrożenie i utrzymanie',
  },
  {
    slug: 'obrazy',
    source: 'docs/container-images.md',
    title: 'Obrazy kontenerowe',
    description: 'Przypięte runtime, build obrazów i kontrola artefaktów.',
    group: 'Wdrożenie i utrzymanie',
  },
  {
    slug: 'k3s-obrazy',
    source: 'docs/k3s-local-images-handoff.md',
    title: 'Lokalne obrazy dla K3s',
    description: 'Opcjonalny import obrazów i granice certyfikacji profilu.',
    group: 'Wdrożenie i utrzymanie',
  },
  {
    slug: 'backup',
    source: 'docs/backup-restore.md',
    title: 'Backup i odtwarzanie',
    description: 'Spójne kopie bazy i obiektów oraz kontrolowane odtworzenie danych.',
    group: 'Wdrożenie i utrzymanie',
  },
  {
    slug: 'srodowisko',
    source: 'docs/environment-variables.md',
    title: 'Zmienne środowiskowe',
    description: 'Konfiguracja usług, plikowe sekrety i profile opcjonalne.',
    group: 'Konfiguracja',
  },
  {
    slug: 'api',
    source: 'docs/api-contracts-baseline.md',
    title: 'Kontrakty API i sesji',
    description: 'Endpointy, role, sesje i wspólne modele WEB oraz Mobile.',
    group: 'Dla programisty',
  },
  {
    slug: 'granice-frontendu',
    source: 'docs/frontend-domain-boundary.md',
    title: 'Granice frontendu i API',
    description: 'Rola TanStack Start, NestJS i zakaz dostępu UI do infrastruktury.',
    group: 'Dla programisty',
  },
  {
    slug: 'zaleznosci',
    source: 'docs/dependency-policy.md',
    title: 'Zależności i toolchain',
    description: 'Bun, kontrolowane aktualizacje i granica TS7/TS6.',
    group: 'Dla programisty',
  },
  {
    slug: 'healthchecki',
    source: 'docs/healthchecks.md',
    title: 'Healthchecki',
    description: 'Liveness, readiness i interpretacja degradacji usług.',
    group: 'Dla operatora',
  },
  {
    slug: 'diagnostyka',
    source: 'docs/compose-smoke-tests.md',
    title: 'Diagnostyka i smoke testy',
    description: 'Rozpoznawanie awarii i izolowana weryfikacja Compose.',
    group: 'Dla operatora',
  },
  {
    slug: 'monitoring',
    source: 'docs/observability.md',
    title: 'Monitoring i logi',
    description: 'Metryki, logi, ślady i alerty w profilach observability.',
    group: 'Dla operatora',
  },
  {
    slug: 'tls',
    source: 'docs/transport-security.md',
    title: 'TLS i mTLS',
    description: 'Tożsamości usług, certyfikaty i granice zaufania.',
    group: 'Dla operatora',
  },
  {
    slug: 'redis',
    source: 'docs/redis-operations.md',
    title: 'Redis i degradacja',
    description: 'Tryby cache, readiness i procedura przy awarii.',
    group: 'Dla operatora',
  },
  {
    slug: 'mobile-start',
    source: 'Mobile/QUICK_START.md',
    title: 'Mobile: pierwsze uruchomienie',
    description: 'Izolowane demo na iOS Simulator i Android Emulator.',
    group: 'Dla klienta Mobile',
  },
  {
    slug: 'mobile-konfiguracja',
    source: 'Mobile/CLIENT_CONFIGURATION.md',
    title: 'Mobile: konfiguracja klienta',
    description: 'Własne miasto, origin API i publiczna konfiguracja.',
    group: 'Dla klienta Mobile',
  },
  {
    slug: 'mobile-build',
    source: 'docs/mobile-build.md',
    title: 'Mobile: build aplikacji',
    description: 'Eksport JS, build natywny i odpowiedzialność za podpisywanie.',
    group: 'Dla klienta Mobile',
  },
  {
    slug: 'mobile-przekazanie',
    source: 'Mobile/CLIENT_HANDOFF.md',
    title: 'Mobile: odbiór i przekazanie',
    description: 'Checklista klienta, utrzymanie i granice gotowości produkcyjnej.',
    group: 'Dla klienta Mobile',
  },
];
export const repository = 'https://github.com/MrDeex1k/ZglosTO/blob/main/';
