apiVersion: v1
kind: Service
metadata:
  name: llm-gateway
  namespace: zglosto
  labels:
    app: llm-gateway
spec:
  selector:
    app: llm-gateway
  ports:
    - name: https
      port: 8130
      targetPort: https
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: llm-gateway-proxy
  namespace: zglosto
  labels:
    app: llm-gateway-proxy
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - name: https
      port: 8443
      protocol: TCP
