apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: zglosto
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: main-app
      port: 1235
      targetPort: http
      protocol: TCP
  type: ClusterIP
