apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: zglosto
  labels:
    app: pgbouncer
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
    - name: postgresql
      port: 6432
      targetPort: postgresql
      protocol: TCP
