apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: zglosto
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: rabbitmq
  ports:
    - name: amqps
      port: 5671
      targetPort: amqps
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: zglosto
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqps
      port: 5671
      targetPort: amqps
      protocol: TCP
