listeners.tcp = none
listeners.ssl.default = 5671

ssl_options.cacertfile = /run/secrets/service/ca.crt
ssl_options.certfile = /run/secrets/service/rabbitmq-server.crt
ssl_options.keyfile = /run/secrets/service/rabbitmq-server.key
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false
ssl_options.versions.1 = tlsv1.3

prometheus.tcp.ip = 0.0.0.0
prometheus.tcp.port = 15692
loopback_users.guest = false

default_queue_type = quorum
consumer_timeout = 900000
disk_free_limit.absolute = 1GB
vm_memory_high_watermark.relative = 0.6
