/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppRegisterRouteImport } from './routes/_app.register'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as AppDashboardAdminRouteImport } from './routes/_app.dashboard.admin'
import { Route as AppDashboardMieszkaniecRouteImport } from './routes/_app.dashboard.mieszkaniec'
import { Route as AppDashboardSluzbyRouteImport } from './routes/_app.dashboard.sluzby'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAdminRoute = AppDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardMieszkaniecRoute = AppDashboardMieszkaniecRouteImport.update({
  id: '/mieszkaniec',
  path: '/mieszkaniec',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSluzbyRoute = AppDashboardSluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/dashboard/admin': typeof AppDashboardAdminRoute
  '/dashboard/mieszkaniec': typeof AppDashboardMieszkaniecRoute
  '/dashboard/sluzby': typeof AppDashboardSluzbyRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/': typeof AppIndexRoute
  '/dashboard/admin': typeof AppDashboardAdminRoute
  '/dashboard/mieszkaniec': typeof AppDashboardMieszkaniecRoute
  '/dashboard/sluzby': typeof AppDashboardSluzbyRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dashboard/admin': typeof AppDashboardAdminRoute
  '/_app/dashboard/mieszkaniec': typeof AppDashboardMieszkaniecRoute
  '/_app/dashboard/sluzby': typeof AppDashboardSluzbyRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/mieszkaniec'
    | '/dashboard/sluzby'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/dashboard/admin'
    | '/dashboard/mieszkaniec'
    | '/dashboard/sluzby'
    | '/dashboard'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/login'
    | '/_app/register'
    | '/_app/'
    | '/_app/dashboard/admin'
    | '/_app/dashboard/mieszkaniec'
    | '/_app/dashboard/sluzby'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/admin': {
      id: '/_app/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AppDashboardAdminRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/mieszkaniec': {
      id: '/_app/dashboard/mieszkaniec'
      path: '/mieszkaniec'
      fullPath: '/dashboard/mieszkaniec'
      preLoaderRoute: typeof AppDashboardMieszkaniecRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/sluzby': {
      id: '/_app/dashboard/sluzby'
      path: '/sluzby'
      fullPath: '/dashboard/sluzby'
      preLoaderRoute: typeof AppDashboardSluzbyRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardAdminRoute: typeof AppDashboardAdminRoute
  AppDashboardMieszkaniecRoute: typeof AppDashboardMieszkaniecRoute
  AppDashboardSluzbyRoute: typeof AppDashboardSluzbyRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAdminRoute: AppDashboardAdminRoute,
  AppDashboardMieszkaniecRoute: AppDashboardMieszkaniecRoute,
  AppDashboardSluzbyRoute: AppDashboardSluzbyRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
