apiVersion: v1
kind: ServiceAccount
metadata:
  name: authorization
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-gateway
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-worker
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgbouncer
  namespace: zglosto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: zglosto
