apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kubernetes

components:
  - ../../components/rustfs
  - ../../components/observability-local

patches:
  - target: { kind: StatefulSet, name: rustfs }
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
  - target: { kind: PersistentVolumeClaim }
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: standard

sortOptions:
  order: legacy
  legacySortOptions:
    orderLast:
      - TriggerAuthentication
      - InterceptorRoute
      - ScaledObject
